name: Daily Orders Sync

on:
  schedule:
    # 6:00 AM IST (00:30 UTC)
    - cron: '30 0 * * *'

    # 1:20 PM IST (07:50 UTC)
    - cron: '50 7 * * *'

  workflow_dispatch: # Allows manual execution from GitHub Actions

jobs:
  run-orders-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas pandas-gbq openpyxl google-auth urllib3

      - name: Verify Files
        run: |
          ls -la

      - name: Run Python Script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: key.json
        run: |
          python "main.py"
